package dev.schwalbe.autovalley.core;
public enum PoiKind { TOMATO_CHEST, WINE_CHEST, WINE_KEG, PRESERVES_JAR, SHIPPING_BIN, DISPOSAL, BED, WAYPOINT, STORAGE_CANDIDATE, WOOD_CHEST, LOGGING_CRAFTING_TABLE }
